services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: true
    tags: [{ name: messenger.message_handler, bus: messenger.bus.query }]

  Core\Application\Exchange\GetAllAvailableExchangesHandler: ~
  Core\Application\Exchange\GetExchangeDetailHandler: ~
  Core\Application\Order\GetOrderHandler: ~
  Core\Application\Credentials\GetCredentialsDetailHandler: ~
  Core\Application\Credentials\GetAllCredentialsHandler: ~
