services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: true
    tags: [{ name: messenger.message_handler, bus: messenger.bus.command }]

  Core\Application\:
    resource: '../../src/Core/Application/*/*CommandHandler.php'
