services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: true
    tags:
      - { name: tactician.handler, typehints: true, bus: query }


  Core\Application\Exchange\GetAllAvailableExchangesHandler: ~
  Core\Application\Exchange\GetExchangeDetailHandler: ~
