parameters:
    # Adds a fallback DATABASE_URL if the env var is not set.
    # This allows you to run cache:warmup even if your
    # environment variables are not available yet.
    # You should not need to change this value.
    env(DATABASE_URL): ''

doctrine:
    dbal:
        # configure these for your database server
        driver: 'pdo_pgsql'
        server_version: 11.1
        charset: utf8
        url: '%env(resolve:DATABASE_URL)%'
        types:
            created_at: Core\Infrastructure\Persistence\Type\DoctrineCreatedAt
            updated_at: Core\Infrastructure\Persistence\Type\DoctrineUpdatedAt
            exchange_id: Core\Infrastructure\Persistence\Type\DoctrineExchangeId
            symbols: Core\Infrastructure\Persistence\Type\DoctrineSymbols
            symbol: Core\Infrastructure\Persistence\Type\DoctrineSymbol
            name: Core\Infrastructure\Persistence\Type\DoctrineName
            order_id: Core\Infrastructure\Persistence\Type\DoctrineOrderId
            order_step_id: Core\Infrastructure\Persistence\Type\DoctrineOrderStepId
            order_step_type: Core\Infrastructure\Persistence\Type\DoctrineStepType
            order_value: Core\Infrastructure\Persistence\Type\DoctrineOrderValue
            executed_at: Core\Infrastructure\Persistence\Type\DoctrineExecutedAt
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true
        mappings:
            Domain:
                is_bundle: false
                type: yml
                dir: '%kernel.project_dir%/src/Core/Infrastructure/Persistence/Orm'
                prefix: 'Core\Domain'
                alias: Domain

