doctrine_migrations:
    dir_name: '%kernel.project_dir%/src/Core/Infrastructure/Persistence/Migrations'
    # namespace is arbitrary but should be different from App\Migrations
    # as migrations classes should NOT be autoloaded
    namespace: Core\Infrastructure\Persistence\Migrations
