tactician:
    default_bus: query
    commandbus:
        query:
            middleware:
                - tactician.commandbus.query.middleware.command_handler
        command:
            middleware:
                - tactician.commandbus.command.middleware.command_handler
