framework:
    messenger:
        transports:
            # Uncomment the following line to enable a transport named "amqp"
            # amqp: '%env(MESSENGER_TRANSPORT_DSN)%'

        routing:
            # Route your messages to the transports
            # 'App\Message\YourMessage': amqp
        buses:
            messenger.bus.command:
                middleware:
                    - doctrine_transaction
                    - Core\Infrastructure\Bus\DomainEventsMiddleware

            messenger.bus.query: ~
            messenger.bus.events: ~
