language: php

php:
  - 7.2

services:
  - docker

install:
  - composer install
  - docker-compose up -d
  - docker exec -it opencrypter-php doctrine:database:create

script:
  - docker exec -it opencrypter-php vendor/bin/phpunit
  - docker exec -it opencrypter-php vendor/bin/behat
