language: php

php:
  - 7.2

services:
  - docker

install:
  - composer install
  - docker-compose up -d

script:
  - docker exec -it opencrypter-php bin/console doctrine:database:create
  - docker exec -it opencrypter-php vendor/bin/phpunit
  - docker exec -it opencrypter-php vendor/bin/behat
