version: '3.3'
services:
  db:
    image: postgres:11.1-alpine
    container_name: opencrypter-postgres
    restart: always
    environment:
      POSTGRES_USER: dbuser
      POSTGRES_PASSWORD: dbpass
      POSTGRES_DB: opencrypter
    ports:
      - 5433:5432
    networks:
      - opencrypter
  php:
    build: ./docker/php-fpm
    container_name: opencrypter-php
    depends_on:
      - "db"
      - "server"
    ports:
      - "9000:9000"
    volumes:
      - .:/app:cached
    extra_hosts:
      - "opencrypter.dev:127.0.0.1"
    networks:
      - opencrypter
  server:
    build: ./docker/nginx
    container_name: opencrypter-server
    restart: always
    ports:
      - "8080:80"
    volumes:
      - ./logs/nginx/:/var/log/nginx:cached
    networks:
      - opencrypter
  start_dependencies:
    image: dadarek/wait-for-dependencies
    depends_on:
      - 'server'
      - 'db'
      - 'php'
    command: db:5432 server:80
    environment:
      SLEEP_LENGTH: 0.5
    networks:
      - opencrypter
networks:
  opencrypter: ~
