version: '3.3'
services:
  db:
    image: postgres:11.1-alpine
    container_name: opencrypter-postgres
    restart: always
    environment:
      POSTGRES_USER: dbuser
      POSTGRES_PASSWORD: dbpass
      POSTGRES_DB: opencrypter
    ports:
      - 5433:5432
  php:
    build: ./docker/php-fpm
    container_name: opencrypter-php
    depends_on:
      - "db"
      - "server"
      - "redis"
      - "rabbitmq"
    ports:
      - "9000:9000"
    volumes:
      - .:/app:cached
    extra_hosts:
      - "opencrypter.dev:127.0.0.1"
  server:
    build: ./docker/nginx
    container_name: opencrypter-server
    restart: always
    ports:
      - "8080:80"
      - "8081:8081"
  redis:
    image: redis
    container_name: opencrypter-redis
    restart: always
    ports:
      - "6379:6379"

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    hostname: rabbitmq
    ports:
      - "15672:15672"
    environment:
      - RABBITMQ_ERLANG_COOKIE=cluster_cookie
      - RABBITMQ_DEFAULT_USER=rabbitmq
      - RABBITMQ_DEFAULT_PASS=rabbitmq

  start_dependencies:
    image: dadarek/wait-for-dependencies
    depends_on:
      - 'server'
      - 'db'
      - 'redis'
      - 'rabbitmq'
      - 'php'
    command: db:5432 server:80 redis:6379
    environment:
      SLEEP_LENGTH: 0.5
