api_login:
    path: /authenticate

api_refresh_token:
    path:     /refresh-token
    defaults: { _controller: gesdinet.jwtrefreshtoken:refresh }

api_register:
    path: /register
    methods: [POST]
    controller: Core\Ui\Http\RegisterUserController::__invoke

all_exchanges:
    path: /v1/exchanges
    methods: [GET]
    controller: Core\Ui\Http\GetAllAvailableExchangesController::__invoke

exchange_detail:
    path: /v1/exchanges/{exchangeId}
    methods: [GET]
    controller: Core\Ui\Http\GetExchangeDetailController::__invoke

orders_put:
    path: /v1/orders/{id}
    methods: [PUT]
    controller: Core\Ui\Http\PutOrderController::__invoke

orders_get:
    path: /v1/orders/{id}
    methods: [GET]
    controller: Core\Ui\Http\GetOrderController::__invoke
