Core\Domain\Exchange\Exchange:
  type: entity
  table: exchange

  id:
    id:
      type: exchange_id
  fields:
    name:
      type: name
    symbols:
      type: symbols
      options:
        jsonb: true
    createdAt:
      type: created_at
    updatedAt:
      type: updated_at
      nullable: true
