Core\Domain\Order\Order:
  type: entity
  table: '"order"'

  id:
    id:
      type: order_id
  fields:
    userId:
      type: user_id
    createdAt:
      type: created_at

  oneToMany:
    steps:
      targetEntity: Core\Domain\Order\Step\Step
      orderBy: { 'position': 'ASC' }
      mappedBy: order
      cascade: ["persist", "merge"]
